[2024-10-27T19:32:21.255+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-27T19:32:21.279+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_demo.train_test_split manual__2024-10-27T19:32:14.838821+00:00 [queued]>
[2024-10-27T19:32:21.294+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_demo.train_test_split manual__2024-10-27T19:32:14.838821+00:00 [queued]>
[2024-10-27T19:32:21.295+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-27T19:32:21.313+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): train_test_split> on 2024-10-27 19:32:14.838821+00:00
[2024-10-27T19:32:21.320+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-27T19:32:21.322+0000] {standard_task_runner.py:72} INFO - Started process 1118 to run task
[2024-10-27T19:32:21.322+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_demo', 'train_test_split', 'manual__2024-10-27T19:32:14.838821+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpaugphvsl']
[2024-10-27T19:32:21.324+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask train_test_split
[2024-10-27T19:32:21.375+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline_demo.train_test_split manual__2024-10-27T19:32:14.838821+00:00 [running]> on host 19d7b464646a
[2024-10-27T19:32:21.456+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline_demo' AIRFLOW_CTX_TASK_ID='train_test_split' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T19:32:14.838821+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T19:32:14.838821+00:00'
[2024-10-27T19:32:21.458+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-27T19:32:21.459+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-27T19:32:21.460+0000] {logging_mixin.py:190} INFO - Current task name:train_test_split state:running start_date:2024-10-27 19:32:21.280775+00:00
[2024-10-27T19:32:21.460+0000] {logging_mixin.py:190} INFO - Dag name:ml_pipeline_demo and current dag run status:running
[2024-10-27T19:32:21.461+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-27T19:32:21.462+0000] {logging_mixin.py:190} INFO - --- Inside train_test_split component ---
[2024-10-27T19:32:21.472+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 29, in train_test_split
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,stratify=y,random_state=47)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 2806, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 2339, in split
    y = check_array(y, input_name="y", ensure_2d=False, dtype=None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 887, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: at least one array or dtype is required
[2024-10-27T19:32:21.724+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-27T19:32:21.726+0000] {logging_mixin.py:190} INFO - Task start:2024-10-27 19:32:21.280775+00:00 end:2024-10-27 19:32:21.724351+00:00 duration:0.443576
[2024-10-27T19:32:21.727+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_test_split> dag:<DAG: ml_pipeline_demo> dagrun:<DagRun ml_pipeline_demo @ 2024-10-27 19:32:14.838821+00:00: manual__2024-10-27T19:32:14.838821+00:00, state:running, queued_at: 2024-10-27 19:32:14.851728+00:00. externally triggered: True>
[2024-10-27T19:32:21.728+0000] {logging_mixin.py:190} INFO - Failure caused by at least one array or dtype is required
[2024-10-27T19:32:21.729+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ml_pipeline_demo, task_id=train_test_split, run_id=manual__2024-10-27T19:32:14.838821+00:00, execution_date=20241027T193214, start_date=20241027T193221, end_date=20241027T193221
[2024-10-27T19:32:21.743+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-27T19:32:21.745+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 76 for task train_test_split (at least one array or dtype is required; 1118)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 29, in train_test_split
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,stratify=y,random_state=47)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 2806, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 2339, in split
    y = check_array(y, input_name="y", ensure_2d=False, dtype=None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 887, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: at least one array or dtype is required
[2024-10-27T19:32:21.781+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-27T19:32:21.805+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-27T19:32:21.811+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
